### ISSUE TITLE
`get_parent_process_exe` can be slow

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1410]
It isn't consistent, but sometimes `get_parent_process_exe` is quite slow, 1.70s in this case:
```
> just unit-tests test_get_parent_process_exe
...
running 1 test
test utils::openers::tests::test_get_parent_process_exe ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 93 filtered out; finished in 1.70s
...
```

I wouldn't be surprised if it's due to the todo:
https://github.com/flox/flox/blob/86c0d47c586fe97cfc624feffeb09227b2a96bfc/cli/flox/src/utils/openers.rs#L135

We need to eliminate whatever is causing the slowdown, as this will cause a noticeable slow down for in-place activations.

**Comment by ysndr** [comment]
@mkenigs do you have some details how to reproduce this? 
It seems rather random, but then noticable according to the description and my memory but i do not managae to reliably see this happening.

**Comment by ysndr** [comment]
I tried to test this with some poor man's benchmark:

```rust
#[test]
fn test_detect_from_parent_process() {
    let mut avg = Duration::from_millis(0);
    let mut min = Duration::from_secs(1000);
    let mut max = Duration::from_millis(0);

    for _loop in 1..=1000 {
        let start = Instant::now();
        let path = get_parent_process_exe().unwrap();
        let duration = start.elapsed();
        avg += duration;
        min = min.min(duration);
        max = max.max(duration);

        println!("Duration: {:?}", duration);
    }

    println!("avg duration: {:?}", avg / 1000);
    println!("min duration: {:?}", min);
    println!("max duration: {:?}", max);
}
```

reading system information has quite a bit of variance in this example from ~5 up to 100+ ms
however the average usually stays < 10ms in my tests.

addressing the todo does not seem to affect the measured durations too much.

**Comment by dcarley** [comment]
Recommendation from refinement was to timebox the effort on investigating this.

We don't currently know if it's affecting activations for real users. Adding permanent benchmarking or fixing telemetry for activations via future watchdog work might help to understand the impact, although with so much happening in activation it might also be hard to tell signal from noise.

@mkenigs do you have any more info about the reproduction of this like what platform it was running on and how often you saw it?

**Comment by mkenigs** [comment]
I don't remember exactly, but I'd guess it only took about 10 runs to see the run I pasted above. I may have been on slow network or under memory or disk pressure. Not sure if those matter. It was an M1 mac.

I think it's worth addressing the TODO, but if we can't reproduce after that I guess we should go ahead and close.

**Comment by ysndr** [comment]
to address the todo you can use this diff:
```diff
diff --git a/cli/flox/src/utils/openers.rs b/cli/flox/src/utils/openers.rs
index 7c3459ed..a7de653e 100644
--- a/cli/flox/src/utils/openers.rs
+++ b/cli/flox/src/utils/openers.rs
@@ -6,7 +6,7 @@ use std::process::Command;
 use anyhow::{anyhow, Context, Result};
 use itertools::Itertools;
 use log::debug;
-use sysinfo::{Pid, System};
+use sysinfo::{Pid, ProcessRefreshKind, RefreshKind, System};
 
 const OPENERS: &[&str] = &["xdg-open", "gnome-open", "kde-open"];
 
@@ -140,8 +140,12 @@ impl Shell {
 }
 
 fn get_parent_process_exe() -> Result<PathBuf> {
-    // todo: we can narrow down the amount of data collected by sysinfo, for now collect everything
-    let system = System::new_all();
+
+    // Read process information from system
+    // We only need the parent process exe, so we only refresh processes and processes' exe
+    let process_refresh_kind = ProcessRefreshKind::new().with_exe(sysinfo::UpdateKind::Always);
+    let refresh_kind = RefreshKind::new().with_processes(process_refresh_kind);
+    let system = System::new_with_specifics(refresh_kind);
 
     let parent_process = system
         .process(Pid::from_u32(std::os::unix::process::parent_id()))
@@ -180,6 +184,8 @@ where
 #[cfg(test)]
 mod tests {
 
+    use std::time::{Duration, Instant};
+
     use super::*;
 
     /// On Linux, Browser::detect() finds xdg-open if it's in path
@@ -256,6 +262,28 @@ mod tests {
         assert!(parent == "cargo" || parent == "cargo-nextest");
     }
 
+    #[test]
+    fn test_detect_from_parent_process() {
+        let mut avg = Duration::from_millis(0);
+        let mut min = Duration::from_secs(1000);
+        let mut max = Duration::from_millis(0);
+
+        for _loop in 1..=1000 {
+            let start = Instant::now();
+            let path = System::new_all();
+            let duration = start.elapsed();
+            avg += duration;
+            min = min.min(duration);
+            max = max.max(duration);
+
+            println!("Duration: {:?}", duration);
+        }
+
+        println!("avg duration: {:?}", avg / 1000);
+        println!("min duration: {:?}", min);
+        println!("max duration: {:?}", max);
+    }
+
     /// Test the detection of the shell from environment variables
     #[test]
     fn test_detect_from_env_var() {
```

this also includes the banchmark thing above

**Comment by dcarley** [comment]
I've been benchmarking the same change this morning but it doesn't appear to make much difference.

Before:

    (2) ~/projects/flox/flox/cli on HEAD (82e818fa) [$]
    % nix run 'nixpkgs#hyperfine' -- --runs=100 --warmup=2 'cargo test tests::test_get_parent_process_exe'
    Benchmark 1: cargo test tests::test_get_parent_process_exe
      Time (mean ± σ):     140.1 ms ±   3.4 ms    [User: 88.7 ms, System: 55.6 ms]
      Range (min … max):   133.1 ms … 158.4 ms    100 runs

      Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet system without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

After:

    (2) ~/projects/flox/flox/cli on dcarley/1410-get-parent-process-exe [$>]
    % nix run 'nixpkgs#hyperfine' -- --runs=100 --warmup=2 'cargo test tests::test_get_parent_process_exe'
    Benchmark 1: cargo test tests::test_get_parent_process_exe
      Time (mean ± σ):     136.8 ms ±   4.5 ms    [User: 80.9 ms, System: 54.4 ms]
      Range (min … max):   130.8 ms … 171.9 ms    100 runs

      Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet system without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

Worth noting that in order to match Matthew's original reproduction:

- I'm measuring `cargo test` so that it's not sharing any state between runs
- I haven't switched to `cargo-nextest` as Matthew's run predated that
- I did add a two pre-runs to exclude any building in a reproducible way

**Comment by mkenigs** [comment]
TODO addressed in https://github.com/flox/flox/pull/1703 and I can't reproduce

**Comment by dcarley** [comment]
@zmitchell can you link the two telemetry tickets (something something Sentry upstream fix and flushing with the watchdog after activation exec) when you've created them, so that we know what's required if we think this is still happening in the future?

**Comment by zmitchell** [comment]
- https://github.com/flox/flox/issues/1711
- https://github.com/flox/flox/issues/1715

**Comment by mkenigs** [comment]
I'm currently seeing these results:
```
$ cargo test -p flox test_detect_from_parent_process -- --nocapture
...
Duration: 9.639049208s
Duration: 64.236333ms
Duration: 8.124838292s
Duration: 676.244542ms
Duration: 6.660007916s
avg duration: 5.032875258s
min duration: 64.236333ms
max duration: 9.639049208s
```
After reworking the test to only do 5 iterations
```
    #[test]
    fn test_detect_from_parent_process() {
        use std::time::{Duration, Instant};

        let mut avg = Duration::from_millis(0);
        let mut min = Duration::from_secs(1000);
        let mut max = Duration::from_millis(0);

        let iterations = 5;
        for _loop in 1..=iterations {
            let start = Instant::now();
            get_parent_process_exe().unwrap();
            let duration = start.elapsed();
            avg += duration;
            min = min.min(duration);
            max = max.max(duration);

            println!("Duration: {:?}", duration);
        }

        println!("avg duration: {:?}", avg / iterations);
        println!("min duration: {:?}", min);
        println!("max duration: {:?}", max);
    }
```
